DROP TABLE IF EXISTS MOVIES;
CREATE TABLE MOVIES AS SELECT * FROM CSVREAD('classpath:movies_data.csv');

DROP TABLE IF EXISTS RATING;
CREATE TABLE RATING (
    id IDENTITY NOT NULL PRIMARY KEY,
    movie_title VARCHAR(500) NOT NULL,
    rating_score NUMERIC(20, 2),
    no_of_rating INT
);